### ISSUE TITLE
Chatgpt shows wrong data when ask about mac os version

### ISSUE THREAD

**Issue by usufjs2002** [openai/following-instructions-human-feedback#5]
![Screenshot_20230126-003256_Chrome](https://user-images.githubusercontent.com/23233915/214718738-ef2fe0c5-ea76-400b-8bcf-fa6d0781da09.jpg)

The Macos version of Monterey is 12.0 where as chatgpt shows as 11.0. The screenshot elaborate the chat content.

As per chatgpt knowledge it has information until Dec 2021. The information about Mac os is available from June 2021. There is an slight glitch in processing the data.

Please check.

Regards
Syed Mohamed Yusuf

**Comment by usufjs2002** [comment]
Mac support link shows to ensure the Mac versions.
[Mac versions ](https://support.apple.com/en-us/HT201260)

**Comment by agentydragon** [comment]
hi, this is not the best place to report chatgpt problems - please use the in-app thumbs-down button to report cases like this
